services:

  # MYSQL DATABASE
  package-db:
    image: mysql:8.4
    container_name: package-db

    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: package_db
      MYSQL_USER: package_user
      MYSQL_PASSWORD: package_password

    ports:
      - "3307:3306"

    volumes:
      - package_mysql_data:/var/lib/mysql

    networks:
      - microservice-network

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "package_user",
          "-ppackage_password"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

   # MONGO DATABASE(BOOKING SERVICE)
  booking-db:
    image: mongo:8
    container_name: booking-db

    environment:
      MONGO_INITDB_ROOT_USERNAME: booking_user
      MONGO_INITDB_ROOT_PASSWORD: booking_password
      MONGO_INITDB_DATABASE: booking_db

    ports:
      - "27018:27017"

    volumes:
      - booking_mongo_data:/data/db

    networks:
      - microservice-network
    
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # POSTGRES DATABASE (ANALYTICS SERVICE)
  analytics-db:
    image: postgres:17

    container_name: analytics-db

    environment:
      POSTGRES_DB: analytics_db
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_password

    ports:
      - "5433:5432"

    volumes:
      - analytics_postgres_data:/var/lib/postgresql/data

    networks:
      - microservice-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U analytics_user -d analytics_db"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  # PACKAGE SERVICE
  package-service:
    build:
      context: ./package-service

    container_name: package-service

    restart: unless-stopped

    ports:
      - "3001:3001"

    environment:
      DB_HOST: package-db
      DB_NAME: package_db
      DB_USER: package_user
      DB_PASSWORD: package_password

    depends_on:
      package-db:
        condition: service_healthy

    networks:
      - microservice-network

# BOOKING SERVICE
  booking-service:
    build: ./booking-service
    
    container_name: booking-service

    restart: unless-stopped
    
    ports:
      - "3002:3002"

    environment:
      PACKAGE_SERVICE_URL: http://package-service:3001
      MONGO_URI: mongodb://booking_user:booking_password@booking-db:27017/booking_db?authSource=admin
    
    depends_on:
      booking-db:
        condition: service_healthy

      package-service:
        condition: service_started
        
    networks:
      - microservice-network


  # ANALYTICS SERVICE
  analytics-service:
    build:
      context: ./analytics-service

    container_name: analytics-service

    restart: unless-stopped

    ports:
      - "5000:5000"

    environment:
      DB_HOST: analytics-db
      DB_NAME: analytics_db
      DB_USER: analytics_user
      DB_PASSWORD: analytics_password

      PACKAGE_SERVICE_URL: http://package-service:3001

    depends_on:
      analytics-db:
        condition: service_healthy

      package-service:
        condition: service_started

    networks:
      - microservice-network


# NETWORK
networks:
  microservice-network:
    driver: bridge


# VOLUME
volumes:
  package_mysql_data:
  booking_mongo_data:
  analytics_postgres_data: